import { ArrowLeft, ExternalLink, Github, Layers3, Mail, Search, ShieldCheck, ShoppingCart, TestTube2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { SafeImage } from '../components/SafeImage';
import { usePageMeta } from '../hooks/usePageMeta';

const research = [
  { value: '39', label: 'participants in the needs-analysis questionnaire' },
  { value: '79.5%', label: 'selected product price comparison as a desired feature' },
  { value: '84.6%', label: 'rated simple/easy-to-use UI as important or very important' },
  { value: '64.1%', label: 'said inaccurate or stale prices could make them stop using the app' },
];

export function PriceWisePage() {
  usePageMeta({ title: 'PriceWise Case Study — Emmanouela Tsakalidou', description: 'Research, UX process and engineering architecture behind PriceWise, a grocery price comparison bachelor thesis prototype.', path: '/projects/pricewise' });
  return <>
    <section className="case-hero section page-top"><div className="container"><Link className="back-link" to="/projects"><ArrowLeft/>All projects</Link><div className="case-hero-grid"><div><p className="eyebrow">Flagship case study · Bachelor thesis</p><h1>PriceWise</h1><p className="case-lead">A full-stack grocery price comparison prototype designed to make it easier to compare products across Greek supermarket websites and organise a shopping list without requiring an account.</p><div className="tag-row"><span className="tag">Full Stack</span><span className="tag">Research</span><span className="tag">UI/UX</span><span className="tag">Manual Testing</span></div><div className="button-row">
  <a
    className="button button--primary"
    href="https://pricewise-web-production.up.railway.app"
    target="_blank"
    rel="noreferrer"
  >
    <ExternalLink />
    Live demo
  </a>

  <a
    className="button button--ghost"
    href="https://github.com/EmmaTsak/pricewise-app"
    target="_blank"
    rel="noreferrer"
  >
    <Github />
    View repository
  </a>
</div></div><div className="case-visual"><SafeImage src={`${import.meta.env.BASE_URL}assets/pricewise-app-home.webp`} alt="Implemented PriceWise compare-prices page in English, showing the navigation, hero message, search field and filters."/><span className="visual-label">Implemented PriceWise interface</span></div></div></div></section>

    <section className="section section--soft"><div className="container"><div className="case-section-head"><p className="eyebrow">The problem</p><h2>Price data exists, but not in one consistent place.</h2><p>Greek supermarket sites differ in structure, naming, categories and availability. Comparing them manually takes time; engineering a unified view also requires collection, normalisation, storage and matching across inconsistent sources.</p></div><div className="research-grid">{research.map((item) => <div className="stat-card" key={item.value}><strong>{item.value}</strong><span>{item.label}</span></div>)}</div></div></section>

    <section className="section"><div className="container"><div className="case-section-head"><p className="eyebrow">UX process</p><h2>Research findings shaped the prototype.</h2><p>The thesis moved from questionnaire findings into requirements, personas, customer journey, Figma mockups, implementation and technical evaluation.</p></div><div className="process-flow" aria-label="PriceWise design process">{['Research','Requirements','Personas','Customer journey','Figma mockups','Implementation','Manual evaluation','Iteration'].map((step, index) => <div key={step}><span>{String(index + 1).padStart(2,'0')}</span><strong>{step}</strong></div>)}</div><div className="persona-grid"><article><span>Persona 01</span><h3>Giorgos · 21 · Student</h3><p>Price-sensitive, comfortable with technology and wants fast product search, nearby supermarket filtering and an account-free list.</p></article><article><span>Persona 02</span><h3>Maria · 35 · Working parent</h3><p>Needs to save time, compare familiar supermarkets and build a simple list she can optionally send by email.</p></article><article><span>Persona 03</span><h3>Nikos · 50 · Household shopper</h3><p>Prefers clear search, readable prices and minimal navigation over feature-heavy workflows.</p></article></div></div></section>

    <section className="section section--soft"><div className="container"><div className="case-section-head"><p className="eyebrow">Implemented application</p><h2>The working prototype, not just the Figma concept.</h2><p>These screenshots show the implemented PriceWise interface: search and filtering, comparable product results, the supermarket comparison modal, the saved shopping list and the responsive mobile layout.</p></div><div className="implementation-gallery"><figure><SafeImage src={`${import.meta.env.BASE_URL}assets/pricewise-app-home.webp`} alt="Implemented PriceWise home page in English with product search and category and store filters."/><figcaption>Compare prices · implemented interface</figcaption></figure><figure><SafeImage src={`${import.meta.env.BASE_URL}assets/pricewise-app-results.webp`} alt="Implemented PriceWise search results showing comparable 7Days products from multiple supermarkets."/><figcaption>Search results · real product data</figcaption></figure><figure><SafeImage src={`${import.meta.env.BASE_URL}assets/pricewise-app-compare.webp`} alt="Implemented PriceWise comparison modal showing the same product from Galaxias and Sklavenitis with prices and add-to-list actions."/><figcaption>Product comparison modal</figcaption></figure><figure><SafeImage src={`${import.meta.env.BASE_URL}assets/pricewise-app-list.webp`} alt="Implemented PriceWise shopping list with a saved product, price, supermarket, remove action and optional email delivery panel."/><figcaption>Shopping list · desktop</figcaption></figure><figure className="implementation-gallery__mobile"><SafeImage src={`${import.meta.env.BASE_URL}assets/pricewise-app-mobile-list.webp`} alt="Implemented PriceWise shopping list on a narrow mobile layout."/><figcaption>Responsive shopping list · mobile</figcaption></figure><figure><SafeImage src={`${import.meta.env.BASE_URL}assets/pricewise-app-privacy.webp`} alt="Implemented PriceWise privacy page showing privacy information, navigation and footer."/><figcaption>Privacy-first product experience</figcaption></figure></div></div></section>

    <section className="section section--soft"><div className="container"><div className="case-section-head"><p className="eyebrow">Design evolution</p><h2>Mockups were a starting point, not a frozen specification.</h2><p>The thesis explicitly records implementation changes, including a product modal and visible EL/EN language switch added after the initial Figma work.</p></div><div className="mockup-gallery"><figure><SafeImage src={`${import.meta.env.BASE_URL}assets/pricewise-home.webp`} alt="Original PriceWise Figma home-page mockup."/><figcaption>Home · original Figma mockup</figcaption></figure><figure><SafeImage src={`${import.meta.env.BASE_URL}assets/pricewise-search.webp`} alt="Original PriceWise Figma search-results mockup."/><figcaption>Search results · original Figma mockup</figcaption></figure><figure><SafeImage src={`${import.meta.env.BASE_URL}assets/pricewise-list.webp`} alt="Original PriceWise Figma shopping-list mockup."/><figcaption>Shopping list · original Figma mockup</figcaption></figure></div></div></section>

    <section className="section"><div className="container"><div className="case-section-head"><p className="eyebrow">Architecture</p><h2>Separated frontend, backend, database and collection workflows.</h2></div><div className="architecture"><div><span>Client</span><strong>React + TypeScript + Vite</strong><small>Axios · react-i18next · socket.io-client</small></div><b>→</b><div><span>API</span><strong>Node.js + Express + TypeScript</strong><small>REST endpoints · Socket.IO · Nodemailer</small></div><b>→</b><div><span>Data</span><strong>PostgreSQL + Prisma</strong><small>Products · supermarkets · categories · comparison groups</small></div></div><div className="architecture secondary"><div><span>Collection</span><strong>Playwright · Cheerio · Axios</strong><small>Source-specific scrapers</small></div><b>→</b><div><span>Schedule</span><strong>node-cron</strong><small>Daily refresh rather than per-search scraping</small></div><b>→</b><div><span>UI refresh</span><strong>Socket.IO events</strong><small>Refresh connected clients after data updates</small></div></div></div></section>

    <section className="section section--soft"><div className="container"><div className="case-section-head"><p className="eyebrow">Core functionality</p><h2>A deliberately focused prototype.</h2></div><div className="feature-grid"><article><Search/><h3>Search & compare</h3><p>Search products and narrow results to selected supermarket chains.</p></article><article><ShoppingCart/><h3>Shopping list</h3><p>Store the list locally without mandatory account creation; optionally email it.</p></article><article><Layers3/><h3>Scheduled data collection</h3><p>Run supermarket-specific scrapers on a controlled schedule rather than every user search.</p></article><article><ShieldCheck/><h3>Privacy-conscious flow</h3><p>Minimise personal-data collection and keep email delivery optional and consent-based.</p></article></div></div></section>

    <section className="section"><div className="container two-column-case"><div><p className="eyebrow">Quality & testing</p><h2>What was actually tested</h2><p>The thesis describes the technical evaluation as primarily manual testing. That distinction matters: Playwright was used for dynamic web scraping, not claimed as end-to-end UI test automation.</p><ul className="check-list"><li><TestTube2/>Frontend navigation and behaviour</li><li><TestTube2/>Adding/removing items and local-list storage</li><li><TestTube2/>Email delivery and language switching</li><li><TestTube2/>Filtering and Socket.IO interface refresh</li><li><TestTube2/>Backend endpoints, database connectivity and scraper behaviour</li><li><TestTube2/>Error handling for incomplete or invalid cases</li></ul></div><div className="callout-card"><span>Future quality work</span><h3>Automated Jest tests were proposed, not fabricated.</h3><p>The thesis identifies unit and integration tests for data cleaning, product normalisation, API endpoints, shopping-list logic and frontend helpers as a future improvement.</p></div></div></section>

    <section className="section section--soft"><div className="container two-column-case"><div><p className="eyebrow">Engineering challenges</p><h2>Where the complexity lives</h2><ul className="bullet-list"><li>Different supermarket HTML structures and JavaScript-loading behaviour</li><li>Selectors and scraping logic that can break when external sites change</li><li>Normalising and matching products with similar names but different quantities or brands</li><li>Keeping the multilingual interface clear without pretending product data is automatically translated</li><li>Balancing data freshness with responsible, limited scraping frequency</li></ul></div><div><p className="eyebrow">Next iterations</p><h2>What I would improve next</h2><ul className="bullet-list"><li>Improve product matching and comparison accuracy</li><li>Run focused usability tests with task-based observations</li><li>Add price history and threshold notifications</li><li>Explore a mobile app with offline shopping-list support</li><li>Add systematic unit and integration testing</li></ul></div></div></section>

    <section className="section"><div className="container contact-card"><div><p className="eyebrow">Explore the code</p><h2>Want to see how PriceWise is structured?</h2><p>The public repository contains the frontend, backend, Docker configuration and scraper workflow.</p></div><div className="contact-actions"><a className="button button--primary" href="https://github.com/EmmaTsak/pricewise-app" target="_blank" rel="noreferrer"><Github/>GitHub repository</a><a className="button button--ghost" href="mailto:tsakalidouemmanouela@gmail.com"><Mail/>Ask me about it</a></div></div></section>
  </>;
}
